sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L1 Power"
    register_type: holding
    address: 622
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L2 Power"
    register_type: holding
    address: 623
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L3 Power"
    register_type: holding
    address: 624
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Power"
    register_type: holding
    address: 625
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Frequency"
    register_type: holding
    address: 609
    unit_of_measurement: "Hz"
    device_class: frequency
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L1 Voltage"
    id: grid_voltage_l1
    register_type: holding
    address: 598
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L2 Voltage"
    id: grid_voltage_l2
    register_type: holding
    address: 599
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid L3 Voltage"
    id: grid_voltage_l3
    register_type: holding
    address: 600
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD
    icon: "mdi:sine-wave"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Power Factor"
    register_type: holding
    address: 621
    unit_of_measurement: "%"
    device_class: power_factor
    accuracy_decimals: 1
    filters:
      - multiply: 0.001
    value_type: U_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Energy Bought"
    id: daily_energy_bought
    register_type: holding
    address: 520
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Daily Energy Sold"
    id: daily_energy_sold
    register_type: holding
    address: 521
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-export"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Energy Bought"
    id: total_energy_bought
    register_type: holding
    address: 522
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-import"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Total Energy Sold"
    id: total_energy_sold
    register_type: holding
    address: 524
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: "total_increasing"
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1
    icon: "mdi:transmission-tower-export"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT L1 Power"
    register_type: holding
    address: 604
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT L2 Power"
    register_type: holding
    address: 605
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT L3 Power"
    register_type: holding
    address: 606
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT Power"
    register_type: holding
    address: 607
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L1 Power"
    register_type: holding
    address: 616
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L2 Power"
    register_type: holding
    address: 617
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L3 Power"
    register_type: holding
    address: 618
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT Power"
    register_type: holding
    address: 619
    unit_of_measurement: "W"
    device_class: power
    accuracy_decimals: 0
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT L1 Current"
    id: internal_ct_l1_current
    register_type: holding
    address: 610
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT L2 Current"
    id: internal_ct_l2_current
    register_type: holding
    address: 611
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "Internal CT L3 Current"
    id: internal_ct_l3_current
    register_type: holding
    address: 612
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L1 Current"
    id: external_ct_l1_current
    register_type: holding
    address: 613
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L2 Current"
    id: external_ct_l2_current
    register_type: holding
    address: 614
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "External CT L3 Current"
    id: external_ct_l3_current
    register_type: holding
    address: 615
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD
    icon: "mdi:transmission-tower"

binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "AC Grid Relay"
    register_type: holding
    address: 552
    bitmask: 0x4
    device_class: power
    icon: "mdi:transmission-tower"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "CT L1 Self Test"
    register_type: holding
    address: 597
    bitmask: 0x01
    device_class: problem
    entity_category: diagnostic
    icon: "mdi:check-circle"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "CT L2 Self Test"
    register_type: holding
    address: 597
    bitmask: 0x02
    device_class: problem
    entity_category: diagnostic
    icon: "mdi:check-circle"

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "CT L3 Self Test"
    register_type: holding
    address: 597
    bitmask: 0x04
    device_class: problem
    entity_category: diagnostic
    icon: "mdi:check-circle"

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Frequency"
    address: 183
    value_type: U_WORD
    entity_category: config
    icon: "mdi:sine-wave"
    optionsmap:
      "50 Hz": 0
      "60 Hz": 1

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "AC Couple"
    address: 234
    value_type: U_WORD
    entity_category: config
    icon: "mdi:power-plug"
    lambda: |-
      if (x != 0 && x != 1 && x != 2) {
        return std::string("Disabled");
      }
      return {};
    optionsmap:
      "Disabled": 0
      "On Grid Side": 1
      "On Load Side": 2

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Grid Voltage"
    address: 138
    value_type: U_WORD
    entity_category: config
    icon: "mdi:transmission-tower"
    optionsmap:
      "LN:220VAC LL:380VAC": 0
      "LN:230VAC LL:398VAC": 1
      "LN:240VAC LL:415VAC": 2
      "LN:120VAC LL:208VAC": 3
      "LN:133VAC LL:220VAC": 4
      "LN:100VAC LL:173VAC": 5

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Charging Signal"
    address: 140
    value_type: U_WORD
    entity_category: config
    icon: "mdi:battery-charging"
    optionsmap:
      "Normal": 0
      "Grid": 1
      "Generator": 2
      "Both": 3

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Force Off Grid"
    id: switch_off_grid
    register_type: holding
    address: 179
    bitmask: 1
    entity_category: config
    icon: "mdi:transmission-tower-off"
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Generator Grid Side"
    register_type: holding
    address: 189
    entity_category: config
    icon: "mdi:generator-stationary"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Asymmetric Phase Feeding"
    register_type: holding
    address: 237
    entity_category: config
    icon: "mdi:transmission-tower"
