# Copyright 2025 Lewa-Reka <lewareka.yt@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

substitutions:
  func_int_to_time: |-
    uint8_t hours = raw / 100;
    uint8_t minutes = raw - (hours * 100);
    return ESPTime {.minute = minutes, .hour = hours};
  func_time_to_int: "return x.hour * 100 + x.minute;"

datetime:
  - platform: template
    name: "Time of Use 1 Start"
    id: time_of_use_1_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_1_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_1_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 2 Start"
    id: time_of_use_2_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_2_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_2_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 3 Start"
    id: time_of_use_3_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_3_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_3_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 4 Start"
    id: time_of_use_4_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_4_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_4_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 5 Start"
    id: time_of_use_5_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_5_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_5_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 6 Start"
    id: time_of_use_6_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_6_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_6_start_raw
          value: !lambda ${func_time_to_int}

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use"
    id: switch_time_of_use
    register_type: holding
    address: 146
    bitmask: 1
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Monday"
    id: switch_time_of_use_monday
    register_type: holding
    address: 146
    bitmask: 2
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Tuesday"
    id: switch_time_of_use_tuesday
    register_type: holding
    address: 146
    bitmask: 4
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Wednesday"
    id: switch_time_of_use_wednesday
    register_type: holding
    address: 146
    bitmask: 8
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Thursday"
    id: switch_time_of_use_thursday
    register_type: holding
    address: 146
    bitmask: 16
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Friday"
    id: switch_time_of_use_friday
    register_type: holding
    address: 146
    bitmask: 32
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Saturday"
    id: switch_time_of_use_saturday
    register_type: holding
    address: 146
    bitmask: 64
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use Sunday"
    id: switch_time_of_use_sunday
    register_type: holding
    address: 146
    bitmask: 128
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Grid Charge"
    id: switch_time_point_1_grid_charge
    register_type: holding
    address: 172
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Gen"
    id: switch_time_point_1_gen
    register_type: holding
    address: 172
    bitmask: 2
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Sell"
    id: switch_time_point_1_sell
    register_type: holding
    address: 172
    bitmask: 32
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Grid Charge"
    id: switch_time_point_2_grid_charge
    register_type: holding
    address: 173
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Gen"
    id: switch_time_point_2_gen
    register_type: holding
    address: 173
    bitmask: 2
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Sell"
    id: switch_time_point_2_sell
    register_type: holding
    address: 173
    bitmask: 32
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Grid Charge"
    id: switch_time_point_3_grid_charge
    register_type: holding
    address: 174
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Gen"
    id: switch_time_point_3_gen
    register_type: holding
    address: 174
    bitmask: 2
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Sell"
    id: switch_time_point_3_sell
    register_type: holding
    address: 174
    bitmask: 32
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Grid Charge"
    id: switch_time_point_4_grid_charge
    register_type: holding
    address: 175
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Gen"
    id: switch_time_point_4_gen
    register_type: holding
    address: 175
    bitmask: 2
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Sell"
    id: switch_time_point_4_sell
    register_type: holding
    address: 175
    bitmask: 32
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Grid Charge"
    id: switch_time_point_5_grid_charge
    register_type: holding
    address: 176
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Gen"
    id: switch_time_point_5_gen
    register_type: holding
    address: 176
    bitmask: 2
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Sell"
    id: switch_time_point_5_sell
    register_type: holding
    address: 176
    bitmask: 32
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Grid Charge"
    id: switch_time_point_6_grid_charge
    register_type: holding
    address: 177
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Gen"
    id: switch_time_point_6_gen
    register_type: holding
    address: 177
    bitmask: 2
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Sell"
    id: switch_time_point_6_sell
    register_type: holding
    address: 177
    bitmask: 32
    icon: "mdi:battery-plus"

number:
  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 1 Start Raw"
    id: time_of_use_1_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 148
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 2 Start Raw"
    id: time_of_use_2_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 149
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 3 Start Raw"
    id: time_of_use_3_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 150
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 4 Start Raw"
    id: time_of_use_4_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 151
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 5 Start Raw"
    id: time_of_use_5_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 152
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 6 Start Raw"
    id: time_of_use_6_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 153
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Voltage"
    id: time_of_use_1_voltage
    register_type: holding
    address: 160
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Voltage"
    id: time_of_use_2_voltage
    register_type: holding
    address: 161
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Voltage"
    id: time_of_use_3_voltage
    register_type: holding
    address: 162
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Voltage"
    id: time_of_use_4_voltage
    register_type: holding
    address: 163
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Voltage"
    id: time_of_use_5_voltage
    register_type: holding
    address: 164
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Voltage"
    id: time_of_use_6_voltage
    register_type: holding
    address: 165
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Out Power"
    id: time_of_use_1_out_power
    unit_of_measurement: W
    device_class: power
    address: 154
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Out Power"
    id: time_of_use_2_out_power
    unit_of_measurement: W
    device_class: power
    address: 155
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Out Power"
    id: time_of_use_3_out_power
    unit_of_measurement: W
    device_class: power
    address: 156
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Out Power"
    id: time_of_use_4_out_power
    unit_of_measurement: W
    device_class: power
    address: 157
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Out Power"
    id: time_of_use_5_out_power
    unit_of_measurement: W
    device_class: power
    address: 158
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Out Power"
    id: time_of_use_6_out_power
    unit_of_measurement: W
    device_class: power
    address: 159
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 SoC"
    unit_of_measurement: "%"
    address: 166
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 SoC"
    unit_of_measurement: "%"
    address: 167
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 SoC"
    unit_of_measurement: "%"
    address: 168
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 SoC"
    unit_of_measurement: "%"
    address: 169
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 SoC"
    unit_of_measurement: "%"
    address: 170
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 SoC"
    unit_of_measurement: "%"
    address: 171
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"
