substitutions:
  func_int_to_time: |-
    uint8_t hours = raw / 100;
    uint8_t minutes = raw - (hours * 100);
    return ESPTime {.minute = minutes, .hour = hours};
  func_time_to_int: "return x.hour * 100 + x.minute;"

datetime:
  - platform: template
    name: "Time of Use 1 Start"
    id: time_of_use_1_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_1_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_1_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 2 Start"
    id: time_of_use_2_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_2_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_2_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 3 Start"
    id: time_of_use_3_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_3_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_3_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 4 Start"
    id: time_of_use_4_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_4_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_4_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 5 Start"
    id: time_of_use_5_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_5_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_5_start_raw
          value: !lambda ${func_time_to_int}

  - platform: template
    name: "Time of Use 6 Start"
    id: time_of_use_6_start
    type: time
    update_interval: 15s
    lambda: |-
      auto raw = id(time_of_use_6_start_raw).state;
      ${func_int_to_time}
    set_action:
      - number.set:
          id: time_of_use_6_start_raw
          value: !lambda ${func_time_to_int}

switch:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use"
    id: switch_time_of_use
    register_type: holding
    address: 248
    bitmask: 1
    icon: "mdi:toggle-switch"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Charge Enable"
    id: switch_time_point_1_charge_enable
    register_type: holding
    address: 274
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Charge Enable"
    id: switch_time_point_2_charge_enable
    register_type: holding
    address: 275
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Charge Enable"
    id: switch_time_point_3_charge_enable
    register_type: holding
    address: 276
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Charge Enable"
    id: switch_time_point_4_charge_enable
    register_type: holding
    address: 277
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Charge Enable"
    id: switch_time_point_5_charge_enable
    register_type: holding
    address: 278
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Charge Enable"
    id: switch_time_point_6_charge_enable
    register_type: holding
    address: 279
    bitmask: 1
    icon: "mdi:battery-plus"

  - platform: template
    name: "Time of Use All Charge Enable"
    id: switch_time_of_use_all_charge_enable
    icon: "mdi:battery-plus"
    optimistic: true
    restore_mode: DISABLED
    disabled_by_default: true
    lambda: |-
      return id(switch_time_point_1_charge_enable).state;
    turn_on_action:
      - switch.turn_on:
          id: switch_time_point_1_charge_enable
      - switch.turn_on:
          id: switch_time_point_2_charge_enable
      - switch.turn_on:
          id: switch_time_point_3_charge_enable
      - switch.turn_on:
          id: switch_time_point_4_charge_enable
      - switch.turn_on:
          id: switch_time_point_5_charge_enable
      - switch.turn_on:
          id: switch_time_point_6_charge_enable
    turn_off_action:
      - switch.turn_off:
          id: switch_time_point_1_charge_enable
      - switch.turn_off:
          id: switch_time_point_2_charge_enable
      - switch.turn_off:
          id: switch_time_point_3_charge_enable
      - switch.turn_off:
          id: switch_time_point_4_charge_enable
      - switch.turn_off:
          id: switch_time_point_5_charge_enable
      - switch.turn_off:
          id: switch_time_point_6_charge_enable

number:
  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 1 Start Raw"
    id: time_of_use_1_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 250
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 2 Start Raw"
    id: time_of_use_2_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 251
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 3 Start Raw"
    id: time_of_use_3_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 252
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 4 Start Raw"
    id: time_of_use_4_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 253
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 5 Start Raw"
    id: time_of_use_5_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 254
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    name: "Time of Use 6 Start Raw"
    id: time_of_use_6_start_raw
    modbus_controller_id: ${modbus_controller_id}
    register_type: holding
    address: 255
    value_type: U_WORD
    min_value: 0
    max_value: 2359
    internal: true

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Voltage"
    id: time_of_use_1_voltage
    register_type: holding
    address: 262
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Voltage"
    id: time_of_use_2_voltage
    register_type: holding
    address: 263
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Voltage"
    id: time_of_use_3_voltage
    register_type: holding
    address: 264
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Voltage"
    id: time_of_use_4_voltage
    register_type: holding
    address: 265
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Voltage"
    id: time_of_use_5_voltage
    register_type: holding
    address: 266
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Voltage"
    id: time_of_use_6_voltage
    register_type: holding
    address: 267
    unit_of_measurement: "V"
    device_class: voltage
    value_type: U_WORD
    multiply: 100
    min_value: 0
    max_value: 63
    step: 0.01
    icon: "mdi:sun-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 Out Power"
    id: time_of_use_1_out_power
    unit_of_measurement: W
    device_class: power
    address: 256
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 Out Power"
    id: time_of_use_2_out_power
    unit_of_measurement: W
    device_class: power
    address: 257
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 Out Power"
    id: time_of_use_3_out_power
    unit_of_measurement: W
    device_class: power
    address: 258
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 Out Power"
    id: time_of_use_4_out_power
    unit_of_measurement: W
    device_class: power
    address: 259
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 Out Power"
    id: time_of_use_5_out_power
    unit_of_measurement: W
    device_class: power
    address: 260
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 Out Power"
    id: time_of_use_6_out_power
    unit_of_measurement: W
    device_class: power
    address: 261
    value_type: U_WORD
    icon: "mdi:power-plug"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 1 SoC"
    id: time_of_use_1_soc
    unit_of_measurement: "%"
    address: 268
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 2 SoC"
    id: time_of_use_2_soc
    unit_of_measurement: "%"
    address: 269
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 3 SoC"
    id: time_of_use_3_soc
    unit_of_measurement: "%"
    address: 270
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 4 SoC"
    id: time_of_use_4_soc
    unit_of_measurement: "%"
    address: 271
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 5 SoC"
    id: time_of_use_5_soc
    unit_of_measurement: "%"
    address: 272
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "Time of Use 6 SoC"
    id: time_of_use_6_soc
    unit_of_measurement: "%"
    address: 273
    min_value: 0
    max_value: 100
    step: 1
    value_type: U_WORD
    icon: "mdi:battery-clock"

  - platform: template
    name: "Time of Use All Voltage"
    id: time_of_use_all_voltage
    unit_of_measurement: "V"
    device_class: voltage
    min_value: 0
    max_value: 63
    step: 0.01
    update_interval: 1s
    icon: "mdi:sun-clock"
    disabled_by_default: true
    lambda: |-
      return id(time_of_use_1_voltage).state;
    set_action:
      - number.set:
          id: time_of_use_1_voltage
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_2_voltage
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_3_voltage
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_4_voltage
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_5_voltage
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_6_voltage
          value: !lambda "return x;"

  - platform: template
    name: "Time of Use All Out Power"
    id: time_of_use_all_out_power
    unit_of_measurement: W
    device_class: power
    min_value: 0
    max_value: 20000
    step: 1
    update_interval: 1s
    icon: "mdi:power-plug"
    disabled_by_default: true
    lambda: |-
      return id(time_of_use_1_out_power).state;
    set_action:
      - number.set:
          id: time_of_use_1_out_power
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_2_out_power
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_3_out_power
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_4_out_power
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_5_out_power
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_6_out_power
          value: !lambda "return x;"

  - platform: template
    name: "Time of Use All SoC"
    id: time_of_use_all_soc
    unit_of_measurement: "%"
    device_class: battery
    min_value: 0
    max_value: 100
    step: 1
    update_interval: 1s
    icon: "mdi:battery-clock"
    disabled_by_default: true
    lambda: |-
      return id(time_of_use_1_soc).state;
    set_action:
      - number.set:
          id: time_of_use_1_soc
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_2_soc
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_3_soc
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_4_soc
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_5_soc
          value: !lambda "return x;"
      - number.set:
          id: time_of_use_6_soc
          value: !lambda "return x;"
