esphome:
  name: deye-inverter-test
  friendly_name: Deye Inverter Test
  min_version: "2025.6.0"
  name_add_mac_suffix: true
  project:
    name: "lewa-reka.esphome-deye-inverter"
    version: "0.1.0"

esp32:
  variant: esp32s3
  framework:
    type: esp-idf

api:

packages:
  pv_inverter:
    url: https://github.com/Lewa-Reka/esphome-deye-inverter
    ref: main
    files: pv_inverter/deye_hybrid_3p_lv.yaml

uart:
  tx_pin: GPIO17
  rx_pin: GPIO18
