esphome:
  devices:
    - id: battery_pack_1
      name: Deye Battery 1

sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Voltage"
    id: bp1_module_voltage
    register_type: holding
    address: 10040
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Current"
    id: bp1_module_current
    register_type: holding
    address: 10041
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Temperature AVG"
    id: bp1_temp_avg
    register_type: holding
    address: 10042
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 2
    filters:
      - multiply: 0.02
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Temperature Cell Max"
    id: bp1_temp_cell_max
    register_type: holding
    address: 10043
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 2
    filters:
      - multiply: 0.02
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Temperature Cell Min"
    id: bp1_temp_cell_min
    register_type: holding
    address: 10044
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 2
    filters:
      - multiply: 0.02
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Temperature MOS Max"
    id: bp1_temp_mos_max
    register_type: holding
    address: 10045
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 2
    filters:
      - multiply: 0.02
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Temperature Heat Mem"
    id: bp1_temp_heat_mem
    register_type: holding
    address: 10046
    unit_of_measurement: "°C"
    device_class: temperature
    accuracy_decimals: 2
    filters:
      - multiply: 0.02
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "SOC"
    id: bp1_soc
    register_type: holding
    address: 10047
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "SOH"
    id: bp1_soh
    register_type: holding
    address: 10048
    unit_of_measurement: "%"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Remaining Capacity"
    id: bp1_remain_capacity
    register_type: holding
    address: 10049
    unit_of_measurement: "Ah"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Total Capacity"
    id: bp1_total_capacity
    register_type: holding
    address: 10050
    unit_of_measurement: "Ah"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Charge Voltage"
    id: bp1_charge_voltage
    register_type: holding
    address: 10051
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Charge Current"
    id: bp1_charge_current
    register_type: holding
    address: 10052
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Discharge Current"
    id: bp1_discharge_current
    register_type: holding
    address: 10053
    unit_of_measurement: "A"
    device_class: current
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Max Cell Voltage"
    id: bp1_max_cell_v
    register_type: holding
    address: 10054
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Min Cell Voltage"
    id: bp1_min_cell_v
    register_type: holding
    address: 10055
    unit_of_measurement: "V"
    device_class: voltage
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Cycle Number"
    id: bp1_cycle_number
    register_type: holding
    address: 10056
    accuracy_decimals: 0
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "MOS Status"
    id: bp1_mos_status
    register_type: holding
    address: 10057
    accuracy_decimals: 0
    value_type: U_WORD

  # Warnings / faults / versions / reserved registers
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Warning 1"
    id: bp1_warning_1
    register_type: holding
    address: 10058
    accuracy_decimals: 0
    value_type: U_WORD
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Warning 2"
    id: bp1_warning_2
    register_type: holding
    address: 10059
    accuracy_decimals: 0
    value_type: U_WORD
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Fault 1"
    id: bp1_fault_1
    register_type: holding
    address: 10060
    accuracy_decimals: 0
    value_type: U_WORD
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Fault 2"
    id: bp1_fault_2
    register_type: holding
    address: 10061
    accuracy_decimals: 0
    value_type: U_WORD
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Software Version"
    id: bp1_software_version
    register_type: holding
    address: 10062
    accuracy_decimals: 0
    value_type: U_WORD
    disabled_by_default: true

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    device_id: battery_pack_1
    name: "Hardware Version"
    id: bp1_hardware_version
    register_type: holding
    address: 10063
    accuracy_decimals: 0
    value_type: U_WORD
    disabled_by_default: true
